-- В pgadmin вначале встать на нужную базу, и только потом вызывать окно sql
-- connect BankTransactionsDB
	
SELECT current_database();

DROP TABLE PUBLIC.TRANSACTIONS;
DROP TABLE PUBLIC.ACCOUNTS;
	
CREATE TABLE PUBLIC.ACCOUNTS (
	ACCOUNTID BIGSERIAL PRIMARY KEY ,
	ACCOUNTNUMBER VARCHAR NOT NULL,
	BALANCE DECIMAL NOT NULL DEFAULT 0
);


CREATE TABLE PUBLIC.TRANSACTIONS (
	TRANSACTIONID BIGSERIAL PRIMARY KEY ,
	ACCOUNTID BIGINT NOT NULL,
	TRANSACTIONTYPE VARCHAR NOT NULL,
	AMOUNT DECIMAL NOT NULL,
	TRANSACTIONDATE TIMESTAMP NOT NULL,
	CONSTRAINT FK_TRANSACTIONS_ACCOUNTS FOREIGN KEY (ACCOUNTID) REFERENCES ACCOUNTS (ACCOUNTID) ON DELETE CASCADE,
	CHECK (
		LOWER(TRANSACTIONTYPE) IN ('deposit', 'withdrawal')
	)
);

