-- В pgadmin вначале встать на нужную базу, и только потом вызывать окно sql
-- connect BankTransactionsDB
	
SELECT current_database();

DROP TABLE PUBLIC.TRANSACTIONS;
DROP TABLE PUBLIC.ACCOUNTS;
	
CREATE TABLE PUBLIC.ACCOUNTS (
	ACCOUNTID BIGSERIAL PRIMARY KEY ,
	ACCOUNTNUMBER VARCHAR NOT NULL,
	BALANCE DECIMAL NOT NULL DEFAULT 0
);

COMMENT ON TABLE ACCOUNTS IS 'Счета клиентов';
COMMENT ON COLUMN ACCOUNTS.ACCOUNTID IS 'ID счета автоинкремент';
COMMENT ON COLUMN ACCOUNTS.ACCOUNTNUMBER IS 'Условный номер счета(симв.)';
COMMENT ON COLUMN ACCOUNTS.BALANCE IS 'Баланс';

CREATE TABLE PUBLIC.TRANSACTIONS (
	TRANSACTIONID BIGSERIAL PRIMARY KEY ,
	ACCOUNTID BIGINT NOT NULL,
	TRANSACTIONTYPE VARCHAR NOT NULL,
	AMOUNT DECIMAL NOT NULL,
	TRANSACTIONDATE TIMESTAMP NOT NULL,
	CONSTRAINT FK_TRANSACTIONS_ACCOUNTS FOREIGN KEY (ACCOUNTID) REFERENCES ACCOUNTS (ACCOUNTID) ON DELETE CASCADE,
	CHECK (
		LOWER(TRANSACTIONTYPE) IN ('deposit', 'withdrawal')
	)
);

COMMENT ON TABLE TRANSACTIONS IS 'Проводки по счетам';
COMMENT ON COLUMN TRANSACTIONS.TRANSACTIONID IS 'ID проводки';
COMMENT ON COLUMN TRANSACTIONS.ACCOUNTID IS 'Ссылка на ID счета';
COMMENT ON COLUMN TRANSACTIONS.TRANSACTIONTYPE IS 'Тип транзакции начисление/списание(deposit/withdrawal)';
COMMENT ON COLUMN TRANSACTIONS.AMOUNT IS 'Сумма транзакции';
COMMENT ON COLUMN TRANSACTIONS.TRANSACTIONDATE IS 'Дата/время транзакции';